canonical/sdcore-gnbsim-k8s-operator

config.yaml, lib/charms/sdcore_amf/v0/fiveg_n2.py, metadata.yaml, requirements.txt, src/charm.py, tests/integration/test_integration.py, tests/unit/test_charm.py
Implements the requirer side of the n2 relation interface:
- Removes `amf_hostname` and `amf_port` from config as they will be retrieved from relation data.
- Adds the relation as a required relation
- Adds unit tests
- Adds dependencies
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Implements the requirer side of the n2 relation interface

src/charm.py, tests/unit/test_charm.py
The integration tests sometimes fail with a `context deadline exceeeded` after 30 seconds. On GitHub runners, resources are limited and it can take longer to execute.
This increases the timeout value to 5 minutes.
=> Increase action execution timeout for integration tests

config.yaml, requirements.txt, src/charm.py, test-requirements.txt, tests/unit/test_charm.py
By default, a `macvlan` interface will use the underlying host's interface with the default gateway. When following the tutorial, all interfaces share the same underlying host's interface.
However, it prevents connectivity with the outside world for real world scenario, like connecting a real `gNodeB`, or deploying the `UPF` on the edge, away from the core.
This change allows specifying what host interface to use for each multus interfaces, allowing the operator to expose the `UPF` to external networks.
When not specifying interfaces, `multus` interfaces will be created with the `bridge` plugin, separating the network traffic in different networks.
=> Add support for specifying underlying host interface to use for RAN network

requirements.txt
Latest `ops` is incompatible with `scenario`. This PR downgrades `ops` version to the latest working one (2.4.1).
=> (Fix) Downgrading version of ops library

tests/integration/test_integration.py
The `tls-certificates` integration is now mandatory on `sdcore-amf-operator` and `sdcore-nfr-operator`.
This integration was missing on the integration test and they failed.
=> Add TLS support missing in integration tests

.github/workflows/main.yaml, lib/charms/sdcore_gnbsim/v0/fiveg_gnb_identity.py, tests/unit/lib/charms/sdcore_gnbsim/v0/test_charms/test_provider_charm/metadata.yaml, tests/unit/lib/charms/sdcore_gnbsim/v0/test_charms/test_provider_charm/src/charm.py, tests/unit/lib/charms/sdcore_gnbsim/v0/test_charms/test_requirer_charm/metadata.yaml, tests/unit/lib/charms/sdcore_gnbsim/v0/test_charms/test_requirer_charm/src/charm.py, tests/unit/lib/charms/sdcore_gnbsim/v0/test_fiveg_gnb_indentity_provider.py, tests/unit/lib/charms/sdcore_gnbsim/v0/test_fiveg_gnb_indentity_requirer.py, tox.ini
This PR add the `fiveg_gnb_identity` relation interface.
The `fiveg_gnb_identity` is a charm relation interface for gNodeBs to share their identity to charms that require those informations. 
**Reference:**
https://docs.google.com/document/d/1s3U82GTUZFJ9mEhiHig0oAl44F0fq3eQT2PNv1uV75g/edit#heading=h.sxnjdvlz6lvq
=> Adding fiveg_gnb_identity relation interface

src/charm.py, tests/integration/test_integration.py, tests/unit/test_charm.py
This PR aims to fix #40. When `fiveg-n2` relation is removed, move into Blocked status.
=> fix: go into blocked status when FiveG-N2 relation is removed

.github/workflows/main.yaml, README.md, lib/charms/sdcore_amf_k8s/v0/fiveg_n2.py, lib/charms/sdcore_gnbsim_k8s/v0/fiveg_gnb_identity.py, metadata.yaml, src/charm.py, test-requirements.txt, tests/integration/test_integration.py, tests/unit/lib/charms/sdcore_gnbsim/v0/test_charms/test_provider_charm/src/charm.py, tests/unit/lib/charms/sdcore_gnbsim/v0/test_charms/test_requirer_charm/src/charm.py, tests/unit/lib/charms/sdcore_gnbsim/v0/test_fiveg_gnb_indentity_requirer.py, tests/unit/test_charm.py
Add -k8s as a suffix in both github and Charmhub name to follow [TE042](https://docs.google.com/document/d/1R0UzoPr3vvorhbBJYBz-5gZkTCTL2a9_R6xV8K4_i-8/edit) . 
- Create new fiveg_identity library
- Pin macaroonbakery to 1.3.2 which installed by juju client indirectly through pytest_operator.
- The next protobuf version 4.21.0 has the breaking changes with the existing code
- https://protobuf.dev/news/2022-05-06/#python-updates
=> chore: Rename SD-Core charms by adding -k8s as a suffix

test-requirements.txt
Revert back to macaroonbakery version update to v1.3.3 which is done by renovate automatically.
=> fix: Revert "chore(deps):update dependency macaroonbakery to v1.3.3"

src/charm.py, tests/unit/test_charm.py
This PRs removes event defers.
Observe update_status and call the centralized _configure method.
Route fiveg_gnb_identity_request event to centralized _configure method.
=> feat: Remove event defer

src/charm.py
The `collect_unit_status` event is triggered after every hook. It will be triggered after N2 relation broken event. So we can remove the handler.
=> chore: use the collect status event to set blocked status on relation broken

config.yaml, lib/charms/sdcore_gnbsim_k8s/v0/fiveg_gnb_identity.py, pyproject.toml, src/charm.py, test-requirements.in, test-requirements.txt, tests/unit/lib/charms/sdcore_gnbsim/v0/test_charms/test_provider_charm/src/charm.py, tests/unit/lib/charms/sdcore_gnbsim/v0/test_charms/test_requirer_charm/src/charm.py, tests/unit/test_charm.py, tox.ini
Move to ruff and codespell for linting. `pyproject-flake8` is currently broken on Python 3.12, making development on Noble break.
=> chore: Move to codespell and ruff 

lib/charms/sdcore_gnbsim_k8s/v0/fiveg_gnb_identity.py, pyproject.toml, tox.ini
Execute codespell over the charm's library on the tox.ini file.
Enable line length check (E501)
=> chore: enable codespell in charm's lib and enable line length check

CONTRIBUTING.md, src/charm.py
We get an hook failed: "storage-attached" failure when multus is not enabled.
This PR fixes it. Now, when Multus is not available in the K8s cluster, the charm remains in BlockedStatus with a proper error message.
=> fix: Charm doesn't handle missing Multus correctly

charmcraft.yaml, src/charm.py, src/templates/config.yaml.j2, tests/unit/expected_config.yaml, tests/unit/test_charm_simulation_action.py
Here we add additional 5G simulation profiles. Now in total we have:
- **register (new)**: Registration procedure
- **pdusessest (existing)**: Registration + UE initiated PDU Session Establishment + User Data packets
- **deregister (new)**: Registration + UE initiated PDU Session Establishment + User Data packets + Deregister
- **anrelease (new)**: Registration + UE initiated PDU Session Establishment + User Data packets + AN Release
- **uetriggservicereq (new)**: Registration + UE initiated PDU Session Establishment + User Data packets + AN Release + UE Initiated Service Request
Those additional profiles increase the level of confidence in our 5G end to end setup as they traverse additional paths and real life conditions in a 5G network.
```
guillaume@thinkpad:~/code/sdcore-gnbsim-rock$ …
```
=> feat: add additional 5G simulation profiles

test-requirements.in, test-requirements.txt, tests/unit/fixtures.py, tests/unit/lib/charms/sdcore_gnbsim/v0/test_fiveg_gnb_indentity_provider.py, tests/unit/lib/charms/sdcore_gnbsim/v0/test_fiveg_gnb_indentity_requirer.py, tests/unit/test_charm_collect_status.py, tests/unit/test_charm_configure.py, tests/unit/test_charm_remove.py, tests/unit/test_charm_simulation_action.py
Now that scenario testing is built into ops we don't need to import it as a separate dependency. Here we use ops.testing instead of scenario. Both have the same API.
=> chore: use built-in testing from ops

.github/workflows/main.yaml, terraform/outputs.tf
This PR removes the job that publishes the `fiveg_gnb_identity` library which was removed [here](https://github.com/canonical/sdcore-gnbsim-k8s-operator/pull/372)
It also update the TF modules.
These are leftover of https://github.com/canonical/sdcore-gnbsim-k8s-operator/pull/372
=> feat: replace fiveg_gnb_identity with fiveg_core_gnb

src/charm.py, tests/integration/fiveg_core_gnb_mock_charm.py, tests/integration/fiveg_n2_mock_charm.py, tests/integration/test_integration.py
There’s a cyclic dependency in the integration tests of AMF, NMS, NRF and GNBSIM which makes bumping release version and publishing very difficult, because the charms depend on each other.
This PR together with https://github.com/canonical/sdcore-nms-k8s-operator/pull/407 removes this dependency
Replacing the AMF with a mock, simplifies the integration test. We are able to remove the NRF, DB and TLS charms which in fact do not interact with the gnbsim
To mock the AMF we use [any_charm](https://github.com/canonical/any-charm). The `fiveg_n2` integration was added [here](https://github.com/canonical/any-charm/pull/33)
=> fix: use AMF mock to remove cyclic dependency in integration tests

charmcraft.yaml, src/charm.py, src/templates/config.yaml.j2, tests/unit/expected_config.yaml, tests/unit/test_charm_simulation_action.py
For GNBSIM release 1.5.0 and higher versions (https://github.com/omec-project/gnbsim/releases/tag/v1.5.0), 
start simulation action outputs are logged under stdout (not stderr). 
Replaces unsupported log level in the configuration template with a supported one. (trace -> debug) 
Fixes: https://github.com/canonical/sdcore-gnbsim-k8s-operator/issues/374
=> fix: check action stdout to evaluate simulation success

src/templates/config.yaml.j2, terraform/main.tf, terraform/variables.tf, tests/unit/expected_config.yaml
This PR fixes [TELCO-1544](https://warthogs.atlassian.net/browse/TELCO-1544)
CONTEXT:
By default, Juju fetches charms with base matching the host OS. It means that when running Jammy, Juju won’t use latest charms, because we’ve changed the base to Noble. 
Adding an optional (as per CC006) config param base will allow using Noble (base should be set to `ubuntu@24.04`) regardless of the host OS.
Enforcing Noble on a Juju model configuration level is not an option, because it breaks COS integration (COS charms are not available in ubuntu@24.04
[TELCO-1544]: https://warthogs.atlassian.net/browse/TELCO-1544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Uses ubuntu@24.04 in TF module and itests

charmcraft.yaml, src/charm.py, src/templates/config.yaml.j2
Gnbsim allows for running simulations for multiple subscribers through the `ueCount` configuration option in each profile. Here we add the ability to configure the subscriber count through a Juju configuration option.
=> feat: add ability to configure subscriber count

tests/integration/test_integration.py
Install hook in the mock charm is failing to find scenario.runtime which is imported from ops.
This causes failure in integration tests.
The scenario.runtime library relies on ops==2.17.x.
Latest version of ops have breaking changes that make these libraries incompatible.
As a workaround we need to pin the ops version until incompatibilities are solved in the dependent projects.
=> fix: pin ops version in the mock charms

charmcraft.yaml, src/charm.py, src/templates/config.yaml.j2, tests/unit/test_charm_collect_status.py
This PR removes the `usim-sequence-number` parameter from the charm configuration, since its value does not affect the simulation.
=> chore: remove Sequence Number from charm configuration
